// EDITE AQUI SOMENTE OS PACOTES QUE DESEJA INSTALAR NO PROJETO
const pacotes = [
    'express',
    'dotenv',
    'pg',
    '@prisma/adapter-pg@7.3.0',
    '--save-dev prisma@7.3.0',
    '@prisma/client@7.3.0',
    '--save-dev nodemon',
];

/*
 *
 * NÃO EDITE DAQUI PARA BAIXO
 *
 */
const apagar = {
    primeiro: ['inicial.js'],
    segundo: ['support.js', 'amods.js'],
};

const criarItens = {
    '.gitignore': {
        codigo: `node_modules/
.env
dist/
build/
*.log
.DS_Store
prisma/migrations/`,
    },

    'package.json': {
        codigo: `{
  "name": "NOME_DA_PASTA",
  "version": "1.0.0",
  "description": "",
  "main": "server.js",
  "type": "module",
  "scripts": {
    "dev": "cls && nodemon src/server.js"
  },
  "keywords": [],
  "author": "",
  "license": "MIT"
}`,
    },

    'ReadMe.MD': {
        codigo: `# 1. Criar projeto
- npm init -y

# 2. Ajustar package.json
- Adicionar: "type": "module"
- Adicionar: "main": "server.js"
- Adicionar dentro do script: "dev": "nodemon server.js"

# 3. Instalar dependência
- npm i express dotenv pg @prisma/client @prisma/adapter-pg
- npm i -D nodemon prisma

# 4. Inicializar Prisma
- npx prisma init --datasource-provider postgresql

# 5. Configurar \`.env\`
- DATABASE_URL="postgresql://usuario:senha@localhost:porta/nome_do_banco_db"

# 6. Configurar schema.prisma
- crie suas tabelas

# 7. Gerar SQL
- npx prisma migrate dev --name init
- npx prisma generate

# 8. Semear dados no banco
- npx prisma db seed

# 9. Abrir Prisma Studio
- npx prisma studio

## Casos de erros

### Após alterar schema.prisma
- npx prisma migrate dev --name nome_da_alteracao (exemplo: adicionar_tabela_users)

### Banco inconsistente (⚠️ APAGA TUDO)
- npx prisma migrate reset

### Apenas popular dados
- npx prisma db seed

### Dicas
|   Comando       | Apaga dados?    | Cria migrations? | Uso            |
| --------------- | ------------    | ---------------- | -------------- |
| \`migrate dev\`   | ❌ Não          | ✅ Sim          | Alterar schema |
| \`db seed\`       | ❌ Não          | ❌ Não          | Popular dados  |
| \`migrate reset\` | ✅ SIM          | ❌ Não          | DEV only       |`,
    },

    '.env': {
        codigo: `DATABASE_URL="postgresql://usuario:senha@localhost:porta/nomeBanco_db"
PORT=3000`,
    },

    'prisma.config.js': {
        codigo: `// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
    schema: 'prisma/schema.prisma',
    migrations: {
        path: 'prisma/migrations',
        seed: 'node prisma/seed.js',
    },
    datasource: {
        url: process.env['DATABASE_URL'],
    },
});`,
    },

    prisma: {
        'schema.prisma': {
            codigo: `generator client {
    provider = "prisma-client-js"
}

datasource db {
    provider = "postgresql"
}

model Exemplo {
    id        Int      @id @default(autoincrement())
    nome      String?
    estado   Boolean  @default(true)
    preco     Decimal  @db.Decimal(10, 2)

    @@map("exemplo")
}`,
        },
        'seed.js': {
            codigo: `import 'dotenv/config';
import pkg from '@prisma/client';
const { PrismaClient } = pkg;
import { PrismaPg } from '@prisma/adapter-pg';
import pg from 'pg';

const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

async function main() {
    console.log('🌱 Resetando tabela exemplo...');

    // Remove todos os registros
    // await prisma.exemplo.deleteMany();

    console.log('📦 Inserindo novos registros...');

    await prisma.exemplo.createMany({
        data: [
            { nome: 'Notebook', preco: 3500.00 },
            { nome: 'Monitor', preco: 1800.00 },
        ],
    });

    console.log('✅ Seed concluído!');
}

main()
    .catch((e) => {
        console.error('❌ Erro no seed:', e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });`,
        },
    },

    src: {
        'server.js': {
            codigo: `import express from 'express';
import 'dotenv/config';
import exemplosRoutes from './routes/exemploRoute.js';

const app = express();
app.use(express.json());

const PORT = process.env.PORT || 3000;

app.get('/', (req, res) => {
    res.send('🚀 API funcionando');
});

// Rotas
app.use('/api', exemplosRoutes);

app.use((req, res) => {
    res.status(404).json({ error: 'Rota não encontrada' });
});

app.listen(PORT, () => {
    console.log(\`🚀 Servidor rodando em http://localhost:\${PORT}\`);
});`,
        },

        utils: {
            'prismaClient.js': {
                codigo: `import pkg from '@prisma/client';
const { PrismaClient } = pkg;
import { PrismaPg } from '@prisma/adapter-pg';
import pg from 'pg';
import 'dotenv/config';

const pool = new pg.Pool({
    connectionString: process.env.DATABASE_URL,
});

const adapter = new PrismaPg(pool);

const prisma = new PrismaClient({ adapter });

export default prisma;`,
            },
        },

        models: {
            'ExemploModel.js': {
                codigo: `import prisma from '../utils/prismaClient.js';

export default class ExemploModel {
    constructor({ id = null, nome = null, estado = true, preco = null } = {}) {
        this.id = id;
        this.nome = nome;
        this.estado = estado;
        this.preco = preco;
    }

    async criar() {
        return prisma.exemplo.create({
            data: {
                nome: this.nome,
                estado: this.estado,
                preco: this.preco,
            },
        });
    }

    async atualizar() {
        return prisma.exemplo.update({
            where: { id: this.id },
            data: { nome: this.nome, estado: this.estado, preco: this.preco },
        });
    }

    async deletar() {
        return prisma.exemplo.delete({ where: { id: this.id } });
    }

    static async buscarTodos(filtros = {}) {
        const where = {};

        if (filtros.nome) where.nome = { contains: filtros.nome, mode: 'insensitive' };
        if (filtros.estado !== undefined) where.estado = filtros.estado === 'true';
        if (filtros.preco !== undefined) where.preco = parseFloat(filtros.preco);

        return prisma.exemplo.findMany({ where });
    }

    static async buscarPorId(id) {
        const data = await prisma.exemplo.findUnique({ where: { id } });
        if (!data) return null;
        return new ExemploModel(data);
    }
}`,
            },
        },

        controllers: {
            'exemploController.js': {
                codigo: `import ExemploModel from '../models/ExemploModel.js';

export const criar = async (req, res) => {
    try {
        if (!req.body) {
            return res.status(400).json({ error: 'Corpo da requisição vazio. Envie os dados!' });
        }

        const { nome, estado, preco } = req.body;

        if (!nome) return res.status(400).json({ error: 'O campo "nome" é obrigatório!' });
        if (preco === undefined || preco === null) return res.status(400).json({ error: 'O campo "preco" é obrigatório!' });

        const exemplo = new ExemploModel({ nome, estado, preco: parseFloat(preco) });
        const data = await exemplo.criar();

        res.status(201).json({ message: 'Registro criado com sucesso!', data });
    } catch (error) {
        console.error('Erro ao criar:', error);
        res.status(500).json({ error: 'Erro interno ao salvar o registro.' });
    }
};

export const buscarTodos = async (req, res) => {
    try {
        const registros = await ExemploModel.buscarTodos(req.query);

        if (!registros || registros.length === 0) {
            return res.status(200).json({ message: 'Nenhum registro encontrado.' });
        }

        res.json(registros);
    } catch (error) {
        console.error('Erro ao buscar:', error);
        res.status(500).json({ error: 'Erro ao buscar registros.' });
    }
};

export const buscarPorId = async (req, res) => {
    try {
        const { id } = req.params;

        if (isNaN(id)) {
            return res.status(400).json({ error: 'O ID enviado não é um número válido.' });
        }

        const exemplo = await ExemploModel.buscarPorId(parseInt(id));

        if (!exemplo) {
            return res.status(404).json({ error: 'Registro não encontrado.' });
        }

        res.json({ data: exemplo });
    } catch (error) {
        console.error('Erro ao buscar:', error);
        res.status(500).json({ error: 'Erro ao buscar registro.' });
    }
};

export const atualizar = async (req, res) => {
    try {
        const { id } = req.params;

        if (isNaN(id)) return res.status(400).json({ error: 'ID inválido.' });

        if (!req.body) {
            return res.status(400).json({ error: 'Corpo da requisição vazio. Envie os dados!' });
        }

        const exemplo = await ExemploModel.buscarPorId(parseInt(id));

        if (!exemplo) {
            return res.status(404).json({ error: 'Registro não encontrado para atualizar.' });
        }

        if (req.body.nome !== undefined) exemplo.nome = req.body.nome;
        if (req.body.estado !== undefined) exemplo.estado = req.body.estado;
        if (req.body.preco !== undefined) exemplo.preco = parseFloat(req.body.preco);

        const data = await exemplo.atualizar();

        res.json({ message: \`O registro "\${data.nome}" foi atualizado com sucesso!\`, data });
    } catch (error) {
        console.error('Erro ao atualizar:', error);
        res.status(500).json({ error: 'Erro ao atualizar registro.' });
    }
};

export const deletar = async (req, res) => {
    try {
        const { id } = req.params;

        if (isNaN(id)) return res.status(400).json({ error: 'ID inválido.' });

        const exemplo = await ExemploModel.buscarPorId(parseInt(id));

        if (!exemplo) {
            return res.status(404).json({ error: 'Registro não encontrado para deletar.' });
        }

        await exemplo.deletar();

        res.json({ message: \`O registro "\${exemplo.nome}" foi deletado com sucesso!\`, deletado: exemplo });
    } catch (error) {
        console.error('Erro ao deletar:', error);
        res.status(500).json({ error: 'Erro ao deletar registro.' });
    }
};`,
            },
        },

        routes: {
            'exemploRoute.js': {
                codigo: `import express from 'express';
import * as controller from '../controllers/exemploController.js';

const router = express.Router();

router.post('/exemplos', controller.criar);
router.get('/exemplos', controller.buscarTodos);
router.get('/exemplos/:id', controller.buscarPorId);
router.put('/exemplos/:id', controller.atualizar);
router.delete('/exemplos/:id', controller.deletar);

export default router;`,
            },
        },
    },
};

export { pacotes, criarItens, apagar };
